### ISSUE TITLE
Has the Zlib license been considered?

### ISSUE THREAD

**Issue by Imberflur** [ryanisaacg/elefont#10]
I am not an expert on this but I have seen compelling [reasons](https://github.com/mooman219/fontdue/issues/7#issuecomment-605861642).

**Comment by elliegoldstein** [comment]
I prefer to stick to MIT/Apache; it's the standard in the Rust ecosystem and the attribution requirement is not especially onerous.

**Comment by Imberflur** [comment]
Just wanted to check :slightly_smiling_face:. Thanks for responding!
