### ISSUE TITLE
Add fontdue support

### ISSUE THREAD

**Issue by elliegoldstein** [ryanisaacg/elefont#4]

**Comment by Imberflur** [comment]
I would be interested in implementing this if I have the time

**Comment by Imberflur** [comment]
https://github.com/Imberflur/elefont/commit/65ab9ca61e6b1c7223a465d513958efa78a210ad

**Comment by elliegoldstein** [comment]
Unfortunately, if we use a git dependency on fontdue then we can't publish it to crates.io. I assume that the fontdue version on crates is a bit old?

**Comment by Imberflur** [comment]
It is a bit old and I initially thought the crates version would be missing necessary features but that does not actually seem to be the case for now. I moved it to the crates version.

**Comment by elliegoldstein** [comment]
Resolved by #11
